apiVersion: v1
kind: Service
metadata:
  # original docker-compose link: "database:mysql.servicecomb.io"
  # Since kubernetes doesn't allow a namespace with dot like "servicecomb.io", make sure the Pod and Service are under the default namespace to be accessible
  name: mysql-test
  labels:
    app: test-mysql
spec:
  ports:
  - port: 3306
    name: http
  selector:
    app: test-mysql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-mysql
        version: v1
    spec:
      containers:
      - name: test-mysql
        image: mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_USER
          value: lance
        - name: MYSQL_PASSWORD
          value: lancepwd
        - name: MYSQL_ROOT_PASSWORD
          value: root
---
