apiVersion: v1
kind: Service
metadata:
  # original docker-compose link: "database:postgresql.servicecomb.io"
  # Since kubernetes doesn't allow a namespace with dot like "servicecomb.io", make sure the Pod and Service are under the default namespace to be accessible
  name: postgresql-client
  labels:
    app: test-database
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: test-database-client
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-database-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-database-client
        version: v1
    spec:
      containers:
      - name: test-client
        image: postgresql-test-client
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        args: ["postgresql-test", "lance", "lancepwd", "testdb"]
        # args:
        # - "postgresql-test"
        # - "lance"
        # - "lancepwd"
        # - "testdb"
