apiVersion: v1
kind: Service
metadata:
  # original docker-compose link: "database:postgresql.servicecomb.io"
  # Since kubernetes doesn't allow a namespace with dot like "servicecomb.io", make sure the Pod and Service are under the default namespace to be accessible
  name: postgresql-test
  labels:
    app: test-database
spec:
  ports:
  - port: 5432
    name: http
  selector:
    app: test-database
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-database
        version: v1
    spec:
      containers:
      - name: test-postgresql
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: testdb
        - name: POSTGRES_USER
          value: lance
        - name: POSTGRES_PASSWORD
          value: lancepwd
---
