apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: baidu
spec:
  destination:
      service: "*.baidu.com"
  ports:
      - port: 443
        protocol: https
      - port: 80
        protocol: http
